# Commented sections below can be used to run tests on the CI server
# https://simulatedgreg.gitbooks.io/electron-vue/content/en/testing.html#on-the-subject-of-ci-testing
version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 10 x64
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  #- yarn test
  - yarn build

test: off

deploy:
  release: 'desktop-surveyv$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: hWuVCUXD59Ar9Hbho74jJrOLqSvJ3S6CqYRjwSDDJT98/Ypics5V+QWZbmel5Wyd
  artifact: /build/*.exe            # upload all NuGet packages to release assets
  on:
    branch: master                 # release from master branch only
